<?php if($this->content['showInfo']): ?>
<a href="/info" class="titleLink"><?php echo $this->__("It seems that you're using LiteNews first time. Click here to view a guide for customizing the service for your purposes."); ?></a>
<?php endif; ?>
<a href="/collection" class="indexLink"><img src="logo/litenews.png" alt="<?php echo $this->__("Collection"); ?>" /></a>
<?php foreach($this->content['websites'] as $website): ?>
<a href="/<?php echo str_replace(" ", "+", $website['name']); ?>" class="indexLink"><img src="logo/<?php echo $website['logo']; ?>" alt="<?php echo $website['name']; ?>" /></a>
<?php endforeach; ?>
<?php if($this->content['feedback']): ?>
<a href="/feedback" class="button"><?php echo $this->__("Send feedback"); ?></a>
<?php endif; ?>
<?php if($this->content['userSettings']): ?>
<a href="/settings" class="button buttonRight"><?php echo $this->__("Settings"); ?></a>
<?php endif; ?>