<?php foreach($this->content['websites'] as $website): ?>
<a href="?page=<?php echo $website['name']; ?>" class="indexLink" onclick="this.className+=' indexLinkActive';"><img src="logo/<?php echo $website['logo']; ?>" alt="<?php echo $website['name']; ?>" /></a>
<?php
endforeach;
if($this->content['userSettings']):
?>
<a href="?page=settings" class="buttonRight" onclick="this.className+=' buttonActive';"><?php echo $this->__("Settings"); ?></a>
<?php endif; ?>