<a href="javascript:window.history.go(-1)" class="button"><?php echo $this->__("Previous page"); ?></a>
<div class="contentBox">
	<p class="contentSubTitle"><?php echo $this->__("Popularity by website"); ?></p>
	<?php
	$multiply = 95 / $this->content['websites'][0]['loads'];
	foreach($this->content['websites'] as $website):
	?>
	<?php $width = $website['loads'] * $multiply; ?>
	<div class="stats" style="width: <?php echo $width; ?>%;">
	<?php echo $website['name']; ?>
	</div>
	<?php endforeach; ?>
</div>
<a href="javascript:window.history.go(-1)" class="button"><?php echo $this->__("Previous page"); ?></a>