<a href="javascript:window.history.go(-1)" class="button"><?php echo $this->__("Previous page"); ?></a>
<div class="contentBox">
<?php foreach($this->content['websites'] as $website): ?>
<?php echo $website['name']; ?><br />
<?php $width = 25 - ($this->content['websites'][0]['loads'] - $website['loads']) / 25; ?>
<div style="margin-bottom: 10px; display: inline-block; overflow: hidden; background: #d3d3d3; width: <?php echo $width; ?>%;">
<?php echo $website['loads']; ?>
</div>
<?php endforeach; ?>
</div>
<a href="javascript:window.history.go(-1)" class="button"><?php echo $this->__("Previous page"); ?></a>