<form action="<?php echo $this->getURL("feedback"); ?>" method="post" name="feedbackForm">
	<a href="<?php echo $this->getURL(); ?>" class="button"><i class="fa fa-angle-double-left"></i><?php echo $this->__("Previous page"); ?></a>
	<a href="javascript:document.feedbackForm.submit();" class="button buttonRight"><i class="fa fa-envelope"></i><?php echo $this->__("Send"); ?></a>
	<?php if(isset($this->content['sendSuccess'])): ?>
	<div class="success"><?php echo $this->__("Feedback succesfully sent"); ?></div>
	<?php elseif(isset($this->content['sendFail'])): ?>
	<div class="error"><?php echo $this->__("Sending feedback failed"); ?></div>
	<?php endif; ?>
	<div class="contentBox">
		<p class="contentSubTitle">
			<?php echo $this->__("Send feedback"); ?>
		</p>
		<select name="feedbackType" id="feedbackType">
			<option value="0" selected="selected"><?php echo $this->__("Choose feedback type"); ?></option>
			<?php foreach(Config::GetPath("local/feedback/feedbackTypes/type", true) as $feedbackKey => $feedbackType): ?>
			<option value="<?php echo $feedbackKey + 1; ?>"><?php echo $this->__($feedbackType); ?></option>
			<?php endforeach; ?>
		</select>
		<br /><br />
		<label for="feedbackEmail"><?php echo $this->__("Email"); ?></label>
		<input type="text" name="feedbackEmail" id="feedbackEmail" />
		<br /><br />
		<label for="feedback"><?php echo $this->__("Feedback"); ?></label>
		<textarea name="feedback" id="feedback"></textarea>
	</div>
	<a href="<?php echo $this->getURL(); ?>" class="button"><i class="fa fa-angle-double-left"></i><?php echo $this->__("Previous page"); ?></a>
	<a href="javascript:document.feedbackForm.submit();" class="button buttonRight"><i class="fa fa-envelope"></i><?php echo $this->__("Send"); ?></a>
</form>