<a href="<?php echo $this->getURL(); ?>" class="button"><?php echo $this->__("Previous page"); ?></a>
<div class="contentBox">
	<p class="contentTitle"><?php echo $this->__("What is LiteNews?"); ?></p>
	<p class="contentText"><?php echo $this->__("LiteNews is a news parser designed for mobile use. It strips images, ads, etc. from websites leaving only the article text."); ?></p>
	<p class="contentText"><?php echo $this->__("So you can browse news more efficiently with minimum network traffic."); ?></p>
</div>
<div class="contentBox">
	<p class="contentTitle"><?php echo $this->__("Using the settings"); ?></p>
	<p class="contentText"><?php echo $this->__("You can access settings page via right bottom corner in main page."); ?></p>
	<p class="contentSubTitle"><?php echo $this->__("Using collection"); ?></p>
	<p class="contentText"><?php echo $this->__("News collection can be accessed by clicking the LiteNews logo in the main page. It lists all news by time order. You can select which websites should be displayed in collection at the settings page."); ?></p>
	<p class="contentSubTitle"><?php echo $this->__("Theme"); ?></p>
	<p class="contentText"><?php echo $this->__("Don't like the colors of the website? You can easily change them by choosing your favourite option in the dropdown menu."); ?></p>
</div>
<a href="<?php echo $this->getURL(); ?>" class="button"><?php echo $this->__("Previous page"); ?></a>