<?php echo $this->getBlock("langswitch"); ?>
<div class="indexDescription">
	<span><?php echo $this->__("All news mixed"); ?></span>
</div>
<a href="<?php echo $this->getURL("collection"); ?>" class="indexLink" tabindex="<?php echo ++$this->content['tabIndex']; ?>">
	<p><?php echo $this->__("All news mixed"); ?></p>
</a>
<a href="<?php echo $this->getURL("weather"); ?>" class="indexLink" tabindex="<?php echo ++$this->content['tabIndex']; ?>">
	<p><?php echo $this->__("Weather"); ?></p>
</a>
<?php foreach($this->content['websites'] as $websiteByLang): ?>
<div class="indexDescription">
	<span><?php echo $this->__("news_".$websiteByLang[0]['language']); ?></span>
</div>
<?php foreach($websiteByLang as $website): ?>
<a href="<?php echo $this->getURL($website['name']); ?>" class="indexLink" tabindex="<?php echo ++$this->content['tabIndex']; ?>">
	<img src="<?php echo $this->getURL("design/img/logo/".$website['logo']); ?>" alt="<?php echo $website['name']; ?>" style="width: <?php echo $website['logoScale']; ?>%;" />
</a>
<?php endforeach; ?>
<?php endforeach; ?>
<?php if($this->content['feedback']): ?>
<?php echo $this->getBlock("button", array('href'=>$this->getURL("feedback"), 'icon'=>"pencil", 'label'=>"Send feedback")); ?>
<?php endif; ?>
<?php echo $this->getBlock("button", array('href'=>"https://github.com/anck69/LiteNews", 'icon'=>"external-link", 'label'=>"GitHub", 'pullRight'=>true, 'external'=>true)); ?>