<div id="top-buttons">
	<?php echo $this->getBlock("button", array('href'=>"/", 'icon'=>"angle-double-left", 'label'=>"Previous page")); ?>
	<?php echo $this->getBlock("button", array('href'=>"#", 'icon'=>"refresh", 'label'=>"Refresh", 'pullRight'=>true, 'customClass'=>"refresh")); ?>
</div>
<?php if(empty($this->content)): ?>
<div class="error"><?php echo $this->__("No articles found"); ?></div>
<?php else: ?>
<div class="weather">
	<div class="contentBox">
		<i class="fa fa-refresh fa-spin"></i>
	</div>
</div>
<?php foreach($this->content['locations'] as $location): ?>
<a href="<?php echo $this->getURL("weather/".$location); ?>" class="titleLink weatherLink" tabindex="<?php echo ++$this->content['tabIndex']; ?>">
	<?php echo print_r($location, true); ?>
</a>
<?php endforeach; ?>
<?php endif; ?>
