<?php if(!isset($content['done'])): ?>
<a href="/install/index.php?step=<?php echo $this->content['step'] + 1; ?>" class="buttonRight">Next step</a>
<div class="contentBox">
	<p class="contentTitle">Step <?php echo $this->content['step']; ?></p>
	<?php if($this->content['step'] == 1): ?>
	<p class="contentText">Open config/xml/database.xml and set your database settings.</p>
	<?php elseif($this->content['step'] == 2): ?>
	<p class="contentText">Open config/xml/local.xml</p>
	<p class="contentText">Set baseURL e.g. "http://example.com/"</p>
	<p class="contentText">Set your admin password for admin panel.</p>
	<?php elseif($this->content['step'] == 3): ?>
	<p class="contentText">Run cron.php every minute.</p>
	<p class="contentText">Set working directory as same where the file exists.</p>
	<p class="contentText">Example: * * * * * cd public_html; php cron.php</p>
	<?php endif; ?>
</div>
<a href="/install/index.php?step=<?php echo $this->content['step'] + 1; ?>" class="buttonRight">Next step</a>
<?php else: ?>
<div class="contentBox">
	<p class="contentTitle">Done!</p>
	<p class="contentText">You can always change your settings afterwards in config/xml directory. After that, log into admin panel and press "Update XML configuration".</p>
	<p class="contentText">Finally you can delete this install directory.</p>
</div>
<a href="<?php echo $this->getURL("admin"); ?>" class="button">Admin panel</a>
<a href="<?php echo $this->getURL(); ?>" class="buttonRight">Main page</a>
<?php endif; ?>