<?php
$class = "button";
if(isset($this->block['pullRight'])) $class .= " buttonRight";
if(isset($this->block['customClass'])) $class .= " ".$this->block['customClass'];
?>
<a href="<?php echo $this->block['href']; ?>" class="<?php echo $class; ?>"<?php if(isset($this->block['external'])) echo ' target="_blank"'; ?>>
	<?php if(isset($this->block['icon']) && !isset($this->block['pullRight'])): ?>
	<i class="fa fa-<?php echo $this->block['icon']; ?>"></i>
	<?php endif; ?>
	<?php if(isset($this->block['label'])): ?>
	<p><?php echo $this->__($this->block['label']); ?></p>
	<?php endif; ?>
	<?php if(isset($this->block['icon']) && isset($this->block['pullRight'])): ?>
	<i class="fa fa-<?php echo $this->block['icon']; ?>"></i>
	<?php endif; ?>
</a>