<form action="<?php echo $this->getURL("admin/feedback"); ?>" method="post" name="adminFeedback">
	<?php echo $this->getBlock("button", array('href'=>$this->getURL("admin"), 'icon'=>"angle-double-left", 'label'=>"Previous page")); ?>
	<?php echo $this->getBlock("button", array('href'=>"javascript:document.adminFeedback.submit();", 'icon'=>"eraser", 'label'=>"Delete", 'pullRight'=>true)); ?>
	<?php if(isset($this->content['feedbacksDeleted'])): ?>
	<div class="success"><?php echo $this->content['feedbacksDeleted']." ".$this->__("feedbacks deleted"); ?></div>
	<?php endif; ?>
	<div class="contentBox">
		<p class="contentText">
			<?php echo $this->__("Page"); ?>&nbsp;
			<select name="feedbackPage" onchange="document.adminFeedback.submit()">
				<?php for($i = 1; $i <= $this->content['feedbackPages']; ++$i): ?>
				<option value="<?php echo $i; ?>"<?php if($this->content['feedbackCurrentPage'] == $i) echo " selected"; ?>><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>
		</p>
		<p class="contentText">
			<?php echo $this->__("Delete feedbacks"); ?>&nbsp;
			<select name="feedbackDeleteMode">
				<option value="1"><?php echo $this->__("Delete selected"); ?></option>
				<option value="2"><?php echo $this->__("Delete current page"); ?></option>
				<option value="3"><?php echo $this->__("Delete all"); ?></option>
			</select>
		</p>
	</div>
	<?php foreach($this->content['feedback'] as $feedback): ?>
	<label for="feedback_<?php echo $feedback['ID']; ?>">
	<div class="contentBox">
		<p class="contentSubTitle">
			<input type="checkbox" class="checkbox" name="feedback_<?php echo $feedback['ID']; ?>" id="feedback_<?php echo $feedback['ID']; ?>" />
			#<?php echo $feedback['ID']; ?>
		</p>
		<p class="contentDate">
			"<?php echo $this->__($this->content['feedbackTypes'][$feedback['Type'] - 1]); ?>" - 
			<?php echo date("d.m.Y H:i:s", $feedback['Timestamp']); ?>
		</p>
		<p class="contentText"><?php echo nl2br(htmlspecialchars($feedback['Content'])); ?></p>
	</div>
	</label>
	<?php endforeach; ?>
	<?php echo $this->getBlock("button", array('href'=>$this->getURL("admin"), 'icon'=>"angle-double-left", 'label'=>"Previous page")); ?>
	<?php echo $this->getBlock("button", array('href'=>"javascript:document.adminFeedback.submit();", 'icon'=>"eraser", 'label'=>"Delete", 'pullRight'=>true)); ?>
</form>