<form action="<?php echo $this->getURL("admin/feedback"); ?>" method="post" name="adminFeedback">
	<a href="<?php echo $this->getURL("admin"); ?>" class="button"><?php echo $this->__("Previous page"); ?></a>
	<a href="javascript:document.adminFeedback.submit();" class="button buttonRight"><?php echo $this->__("Delete"); ?></a>
	<?php if(isset($this->content['feedbacksDeleted'])): ?>
	<div class="success"><?php echo $this->content['feedbacksDeleted']." ".$this->__("feedbacks deleted"); ?></div>
	<?php endif; ?>
	<div class="contentBox">
		<p class="contentText">
			<?php echo $this->__("Page"); ?>&nbsp;
			<select name="feedbackPage" onchange="document.adminFeedback.submit()">
				<?php for($i = 1; $i <= $this->content['feedbackPages']; ++$i): ?>
				<option value="<?php echo $i; ?>"<?php if($this->content['feedbackCurrentPage'] == $i) echo " selected"; ?>><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>
		</p>
		<p class="contentText">
			<?php echo $this->__("Delete feedbacks"); ?>&nbsp;
			<select name="feedbackDeleteMode">
				<option value="1"><?php echo $this->__("Delete selected"); ?></option>
				<option value="2"><?php echo $this->__("Delete current page"); ?></option>
				<option value="3"><?php echo $this->__("Delete all"); ?></option>
			</select>
		</p>
	</div>
	<?php foreach($this->content['feedback'] as $feedback): ?>
	<label for="feedback_<?php echo $feedback['ID']; ?>">
	<div class="contentBox">
		<p class="contentSubTitle">
			<input type="checkbox" name="feedback_<?php echo $feedback['ID']; ?>" id="feedback_<?php echo $feedback['ID']; ?>" />
			#<?php echo $feedback['ID']; ?>
		</p>
		<p class="contentDate">
			"<?php echo $this->__($this->content['feedbackTypes'][$feedback['Type'] - 1]); ?>" - 
			<?php echo date("d.m.Y H:i:s", $feedback['Timestamp']); ?>
		</p>
		<p class="contentText"><?php echo htmlspecialchars($feedback['Content']); ?></p>
	</div>
	</label>
	<?php endforeach; ?>
	<a href="<?php echo $this->getURL("admin"); ?>" class="button"><?php echo $this->__("Previous page"); ?></a>
	<a href="javascript:document.adminFeedback.submit();" class="button buttonRight"><?php echo $this->__("Delete"); ?></a>
</form>