<form action="<?php echo $this->getURL("admin"); ?>" method="post" name="adminLogin">
	<?php echo $this->getBlock("button", array('href'=>$this->getURL(), 'icon'=>"angle-double-left", 'label'=>"Previous page")); ?>
	<?php echo $this->getBlock("button", array('href'=>"javascript:document.adminLogin.submit();", 'icon'=>"sign-in", 'label'=>"Login", 'pullRight'=>true)); ?>
	<?php if(isset($this->content['logout'])): ?>
	<div class="success"><?php echo $this->__("Logged out"); ?></div>
	<?php elseif(isset($this->content['maxLoginFails'])): ?>
	<div class="error"><?php echo $this->__("Maximum limit of login attempts reached"); ?></div>
	<?php elseif(isset($this->content['loginFail'])): ?>
	<div class="error"><?php echo $this->__("Incorrect password"); ?></div>
	<?php endif; ?>
	<div class="contentBox">
		<p class="contentTitle"><?php echo $this->__("Admin panel"); ?></p>
		<p class="contentText">
			<label for="adminPassword"><?php echo $this->__("Password"); ?></label>
		</p>
		<input type="password" name="adminPassword" id="adminPassword" />
	</div>
	<?php echo $this->getBlock("button", array('href'=>$this->getURL(), 'icon'=>"angle-double-left", 'label'=>"Previous page")); ?>
	<?php echo $this->getBlock("button", array('href'=>"javascript:document.adminLogin.submit();", 'icon'=>"sign-in", 'label'=>"Login", 'pullRight'=>true)); ?>
</form>